version: '3.4'

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    ports:
      - 4444:4444
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
  
  mongodb: 
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
        
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json