version: '3.4'

services:
  zookeeper:
    image: zookeeper:3.5.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_CFG_EXTRA: zookeeper.session.timeout.ms=12000 zookeeper.connection.timeout.ms=12000 zookeeper.sync.time.ms=4000
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "updates:1:1, configs:1:1, tests:1:1"
    depends_on:
      - zookeeper

  mongodb: 
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
        
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json