apiVersion: v1
kind: Service
metadata:
  labels:
    app: chrome
  name: chrome
spec:
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
  selector:
    app: chrome
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chrome
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Dwebdriver.chrome.whitelistedIps=
          name: chrome
          image: selenium/standalone-chrome:latest
          resources: { }
      restartPolicy: Always