apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: feedsscraper
  name: feedsscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedsscraper
  template:
    metadata:
      labels:
        app: feedsscraper
    spec:
      containers:
        - image: irisupdate/feedsscraper:latest
          imagePullPolicy: "Always"
          name: feedsscraper
      restartPolicy: Always