apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messagesmanager
  name: messagesmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagesmanager
  template:
    metadata:
      labels:
        app: messagesmanager
    spec:
      containers:
        - image: irisupdate/messagesmanager:latest
          imagePullPolicy: "Always"
          name: messagesmanager
          env:
            - name: SubscriptionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: connectionstring
            - name: UpdatesDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: updatesdbsecrets
                  key: connectionstring
      restartPolicy: Always