apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscriptionsmanager
  name: subscriptionsmanager
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: subscriptionsmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subscriptionsmanager
  name: subscriptionsmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionsmanager
  template:
    metadata:
      labels:
        app: subscriptionsmanager
    spec:
      containers:
        - image: irisupdate/subscriptionsmanager:latest
          imagePullPolicy: "Always"
          name: subscriptionsmanager
          env:
            - name: SubscriptionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: connectionstring
      restartPolicy: Always