apiVersion: v1
kind: Secret
metadata:
  name: subscriptionsmanagersecrets
type: Opaque
stringData:
  sentry: https://0b05f692e49849bcb942822c87a55612@o194751.ingest.sentry.io/5577476
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: subscriptionsmanager
  name: subscriptionsmanager
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app: subscriptionsmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subscriptionsmanager
  name: subscriptionsmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionsmanager
  template:
    metadata:
      labels:
        app: subscriptionsmanager
    spec:
      containers:
        - image: irisupdate/subscriptionsmanager:latest
          imagePullPolicy: "Always"
          name: subscriptionsmanager
          env:
            - name: RabbitMqConnection__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecrets
                  key: connectionstring
            - name: SubscriptionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: connectionstring
            - name: SubscriptionsDb__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: databasename
            - name: Sentry__Dsn
              valueFrom:
                secretKeyRef:
                  name: subscriptionsmanagersecrets
                  key: sentry
      restartPolicy: Always