apiVersion: v1
kind: Secret
metadata:
  name: telegramreceiversecrets
type: Opaque
stringData:
  accesstoken: accesstoken
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegramreceiver
  name: telegramreceiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramreceiver
  template:
    metadata:
      labels:
        app: telegramreceiver
    spec:
      containers:
        - image: irisupdate/telegramreceiver:latest
          imagePullPolicy: "Always"
          name: telegramreceiver
          env:
            - name: SubscriptionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: connectionstring
            - name: ConnectionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: connectionsdbsecrets
                  key: connectionstring
            - name: Telegram__AccessToken
              valueFrom:
                secretKeyRef:
                  name: telegramreceiversecrets
                  key: accesstoken
            - name: Telegram__DefaultInterval
              value: "00:01:00"
            - name: Twitter__ConsumerKey
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: consumerkey
            - name: Twitter__ConsumerSecret
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: consumersecret
            - name: Facebook__PageCount
              value: "1"
      restartPolicy: Always