apiVersion: v1
kind: Secret
metadata:
  name: telegramsendersecrets
type: Opaque
stringData:
  bottoken: 1296985114:AAEHzJwBLsqwyItRTf74znQmbqEWVbbzfnw
  appid: "2796714"
  apphash: 44eae6e9ec943d9d701c9f4b567dbc9e
  sentry: https://ddf6f2983489423290e3d6753ae6734e@o194751.ingest.sentry.io/5428167
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegramsender
  name: telegramsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramsender
  template:
    metadata:
      labels:
        app: telegramsender
    spec:
      containers:
        - image: irisupdate/telegramsender:latest
          imagePullPolicy: "Always"
          name: telegramsender
          env:
            - name: RabbitMqConnection__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecrets
                  key: connectionstring
            - name: Telegram__BotToken
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: bottoken
            - name: Telegram__AppId
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: appid
            - name: Telegram__AppHash
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: apphash
            - name: SubscriptionsDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: connectionstring
            - name: SubscriptionsDb__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: subscriptionsdbsecrets
                  key: databasename
            - name: Sentry_Dsn
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: sentry
      restartPolicy: Always