apiVersion: v1
kind: Secret
metadata:
  name: telegramsendersecrets
type: Opaque
stringData:
  bottoken: bottoken
  appid: appid
  apphash: apphash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegramsender
  name: telegramsender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegramsender
  template:
    metadata:
      labels:
        app: telegramsender
    spec:
      containers:
        - image: irisupdate/telegramsender:latest
          imagePullPolicy: "Always"
          name: telegramsender
          env:
            - name: Telegram__BotToken
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: bottoken
            - name: Telegram__AppId
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: appid
            - name: Telegram__AppHash
              valueFrom:
                secretKeyRef:
                  name: telegramsendersecrets
                  key: apphash
      restartPolicy: Always