apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twitterscraper
  name: twitterscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterscraper
  template:
    metadata:
      labels:
        app: twitterscraper
    spec:
      containers:
        - image: irisupdate/twitterscraper:latest
          imagePullPolicy: "Always"
          name: twitterscraper
          env:
            - name: RabbitMqConnection__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: rabbitmqsecrets
                  key: connectionstring
            - name: UpdatesScraperDb__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: connectionstring
            - name: UpdatesScraperDb__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: databasename
            - name: UpdatesProvider__ConsumerKey
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: consumerkey
            - name: UpdatesProvider__ConsumerSecret
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: consumersecret
            - name: Sentry__Dsn
              valueFrom:
                secretKeyRef:
                  name: twittersecrets
                  key: sentry
      restartPolicy: Always
