apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: facebookscraper
  name: facebookscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: facebookscraper
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/mongodb_network: "true"
        io.kompose.network/rabbitmq_network: "true"
        io.kompose.service: facebookscraper
    spec:
      containers:
      - image: irisupdate/facebookscraper:latest
        imagePullPolicy: ""
        name: facebookscraper
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
