name: FacebookScraper

on:
  push:
    branches: [ master ]
    paths:
      - "Extensions/**"
      - "Common/**"
      - "UpdatesScraper/**"
      - "FacebookScraper/**"
    
jobs:
  build-push:
    name: Build image and push to container registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          file: ./FacebookScraper/Dockerfile
          push: true
          tags: irisupdate/facebookscraper:latest

  deploy:
    name: Deploy new image
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save iris
      - name: Update deployment
        run: |
          - kubectl set image deployment facebookscraper facebookscraper=irisupdate/facebookscraper:latest
          - kubectl set image deployment facebookscraper facebookscraper=irisupdate/facebookscraper
