name: SubscriptionsManager

on:
  workflow_dispatch:
  v4
    branches: [ v4 ]
    paths:
      - "Extensions/**"
      - "Common/**"
      - "SubscriptionsDb/**"
      - "SubscriptionsManager/**"

jobs:
  build-v4:
    name: Build image and push to container registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          file: ./SubscriptionsManager/Dockerfile
          v4 true
          tags: irisupdate/subscriptionsmanager:latest
          