name: build

on: push

jobs:
  build:
    name: Build and push TelegramReceiver image
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          file: ./TelegramReceiver/Dockerfile
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: irisupdate/telegramreceiver:latest  
